version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - user-db
    networks:
      - hotel-net

  room-service:
    build:
      context: ./room-service
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - room-db
    networks:
      - hotel-net

  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    ports:
     
